use chrono::Local;

use super::daily::SummaryCard;

/// Templates for generating Obsidian-compatible Markdown files
pub struct Templates;

impl Templates {
    /// Generate session archive frontmatter and content
    #[allow(clippy::too_many_arguments)]
    pub fn session_archive(
        title: &str,
        date: &str,
        session_id: &str,
        cwd: &str,
        git_branch: Option<&str>,
        transcript_path: Option<&str>,
        summary: &str,
        decisions: &str,
        code_changes: &str,
        learnings: &str,
        skill_hints: &str,
    ) -> String {
        let created = Local::now().to_rfc3339();
        let git_branch_str = git_branch.unwrap_or("N/A");
        let transcript_path_str = transcript_path.unwrap_or("N/A");

        format!(
            r#"---
title: "{title}"
date: {date}
session_id: {session_id}
cwd: "{cwd}"
git_branch: "{git_branch_str}"
transcript_path: "{transcript_path_str}"
tags: [claude-code, session-archive]
created: {created}
---

# {title}

## Context

- **Working Directory**: `{cwd}`
- **Git Branch**: `{git_branch_str}`

## Summary

{summary}

## Key Decisions & Trade-offs

{decisions}

## Code Changes

{code_changes}

## Learnings

{learnings}

## Potential Skills/Commands

{skill_hints}

---
*Archived by Daily Context Archive System*
"#
        )
    }

    /// Generate daily summary frontmatter and content
    #[allow(clippy::too_many_arguments)]
    pub fn daily_summary(
        date: &str,
        session_count: usize,
        overview: &str,
        session_details: &str,
        insights: &[SummaryCard],
        skills: &[SummaryCard],
        commands: &[SummaryCard],
        reflections: &str,
        tomorrow_focus: &[SummaryCard],
    ) -> String {
        let updated = Local::now().to_rfc3339();

        let insights_md = Self::render_cards(insights);
        let skills_md = Self::render_cards(skills);
        let commands_md = Self::render_cards(commands);
        let tomorrow_md = Self::render_cards(tomorrow_focus);

        format!(
            r#"---
date: {date}
updated: {updated}
tags: [daily-summary, claude-code]
session_count: {session_count}
---

# Daily Summary - {date}

## Overview

{overview}

## Key Work

{session_details}

## Key Insights

{insights_md}

## Reflections

{reflections}

## Tomorrow's Focus

{tomorrow_md}

## Skills & Commands Identified

### Potential Skills

{skills_md}

### Potential Commands

{commands_md}

---
*Generated by Daily Context Archive System*
*Last updated: {updated}*
"#
        )
    }

    /// Render a slice of SummaryCards as markdown subsections
    fn render_cards(cards: &[SummaryCard]) -> String {
        if cards.is_empty() {
            return String::new();
        }
        cards
            .iter()
            .map(|card| format!("### {}\n\n{}", card.title, card.content))
            .collect::<Vec<_>>()
            .join("\n\n")
    }

    /// Generate a minimal daily.md for a new day
    pub fn daily_init(date: &str) -> String {
        let created = Local::now().to_rfc3339();

        format!(
            r#"---
date: {date}
created: {created}
updated: {created}
tags: [daily-summary, claude-code]
session_count: 0
---

# Daily Summary - {date}

## Overview

_No sessions archived yet._

## Sessions

## Key Insights

## Skills & Commands Identified

### Potential Skills

### Potential Commands

## Reflections

## Tomorrow's Focus

---
*Generated by Daily Context Archive System*
"#
        )
    }

    /// Generate skill template
    #[allow(dead_code)]
    pub fn skill(name: &str, description: &str, trigger: &str, workflow: &str) -> String {
        let timestamp = Local::now().to_rfc3339();

        format!(
            r#"---
name: {name}
description: "{description}"
metadata:
  version: 1.0.0
  generated_by: daily
  generated_at: {timestamp}
---

# {name}

{description}

## Trigger

Use this skill when: {trigger}

## Workflow

{workflow}

## Examples

_Add examples based on your usage patterns._

---
*Generated from daily archive insights*
"#
        )
    }

    /// Generate command template
    #[allow(dead_code)]
    pub fn command(name: &str, description: &str, use_case: &str, content: &str) -> String {
        format!(
            r#"---
description: "{description}"
---

# {name}

{use_case}

{content}
"#
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_session_archive_template() {
        let content = Templates::session_archive(
            "Test Session",
            "2026-01-16",
            "abc123",
            "/home/user/project",
            Some("main"),
            Some("/path/to/transcript.jsonl"),
            "Test summary",
            "Test decisions",
            "Test changes",
            "Test learnings",
            "Test hints",
        );

        assert!(content.contains("title: \"Test Session\""));
        assert!(content.contains("session_id: abc123"));
        assert!(content.contains("transcript_path:"));
    }

    #[test]
    fn test_daily_init_template() {
        let content = Templates::daily_init("2026-01-16");
        assert!(content.contains("date: 2026-01-16"));
        assert!(content.contains("session_count: 0"));
    }
}
